// Generated by CoffeeScript 1.4.0

/*
Define Sammy.js application.
*/


(function() {
  var app;

  app = $.sammy("#page-content", function() {
    this.use(Sammy.Template, "tpl");
    this.get("#/project/:name", function() {
      console.log("project " + this.params.name);
      return this.partial("tpl/project.tpl", {
        name: this.params.name
      }, function() {
        return $("img").load(function() {
          return $('.gallery').isotope({
            layoutModeString: 'masonry'
          });
        });
      });
    });
    return this.get("/", function() {
      return this.partial("tpl/gallery.tpl", {}, function() {
        return new CoolGallery("#gallery-container", {
          galleryDir: "portfolio",
          realWidth: "100%",
          realHeight: "75%",
          columns: 3,
          width: 1000,
          height: 600,
          paddingTop: 10,
          paddingBottom: 0,
          paddingLeft: 10,
          paddingRight: 10,
          titleFromLeft: 10,
          tittlePadding: 20,
          photosData: {
            width: 300,
            height: 300,
            symbolWidth: 190,
            symbolHeight: 120,
            charge: -100,
            z: 1
          },
          repulsionMult: 130,
          hrefFunc: function(d) {
            return "#/project/" + d.dir;
          }
        });
      });
    });
  });

  $(function() {
    return app.run();
  });

}).call(this);
